### ISSUE TITLE
[Recipe] Join list of strings with delimiter

### ISSUE THREAD

**Issue by jcubic** [schemedoc/cookbook#10]
## Problem
You have a list of strings and string delimiter and you want to create a single string from the list with a delimiter in between

## Solution
```scheme
(define (string-join list delimiter)
  (let iter ((list list) (result '()))
    (if (null? list)
        (apply string-append (reverse result))
        (let ((item (car list))
              (rest (cdr list)))
          (if (null? result)
              (iter rest (cons item result))     
              (iter rest (cons item (cons delimiter result))))))))
```

Credit @jcubic 

### Alternative
Alternative using string ports
```scheme
(define (string-join list delimiter)
  (if (null? list) ""
      (call-with-port (open-output-string)
                      (lambda (out)
                        (write-string (car list) out)
                        (for-each (lambda (item)
                                    (write-string delimiter out)
                                    (write-string item out))
                                  (cdr list))
                        (get-output-string out)))))
```
Credit @lassik 

### SRFI
you can use SRFI-13 that provides `string-join` function.

## Usage
```scheme
(string-join '("foo" "bar" "baz") ":")
;; ==> "foo:bar:baz"
```

**Comment by lassik** [comment]
Your solution works fine as is.

A couple of hints for efficiency:

* The `(if (null? result) ...)` check can be done once, before the loop. It doesn't need to be done on each iteration.
* Carrying the result as a string, and using `string-append` on each iteration of the loop, is probably more efficient than gathering the strings into a temporary list. Avoiding `apply` will also avoid implementation limits on how many args can be passed to a procedure (if `list` is very long, it can exceed the limit).

This procedure can also be written using `fold`.

**Comment by lassik** [comment]
Another way is to use string ports (the standard `open-output-string`, or the non-standard `with-output-to-string`).

**Comment by APIPLM** [comment]
`string-join` in SRFI-13 need the symbol `grammar`, which is not in MIT Scheme as `load srfi-13.scm` . In MIT Scheme  there is another way to do that in MIT Scheme
```
((string-joiner* 'infix ", " 'prefix "<" 'suffix ">")
 '("a" "b" "c"))
```

**Comment by lassik** [comment]
MIT Scheme is more than 30 years old. That procedure may be older than SRFI 13.

**Comment by lassik** [comment]
Here's the version with the null check done once before the loop:

```Scheme
(define (string-join list delimiter)
  (if (null? list) ""
      (let iter ((list (cdr list)) (result (car list)))
        (if (null? list) result
            (iter (cdr list) (string-append result delimiter (car list)))))))
```

Here's the version using fold:

```Scheme
(define (string-join list delimiter)
  (if (null? list) ""
      (fold (lambda (item result) (string-append result delimiter item))
            (car list)
            (cdr list))))
```

**Comment by lassik** [comment]
Here's the one using a string port:

```Scheme
(define (string-join list delimiter)
  (if (null? list) ""
      (call-with-port (open-output-string)
                      (lambda (out)
                        (write-string (car list) out)
                        (for-each (lambda (item)
                                    (write-string delimiter out)
                                    (write-string item out))
                                  (cdr list))
                        (get-output-string out)))))
```

**Comment by lassik** [comment]
Committed into the file `join-list-of-strings-with-delimiter.md`.

**Comment by lassik** [comment]
Now at https://cookbook.scheme.org/join-list-of-strings-with-delimiter/
