### ISSUE TITLE
[Recipe] Format Unix timestamp

### ISSUE THREAD

**Issue by lassik** [schemedoc/cookbook#13]
## Problem
Given an integer saying the number of seconds since the Unix epoch (1970-01-01 00:00:00) format it as a human-readable date and time string.

### SRFI
Using SRFI-19
```scheme
(define (time-unix->time-utc seconds)
  (add-duration (date->time-utc (make-date 0 0 0 0 1 1 1970 0))
                (make-time time-duration 0 seconds)))

(define (time-unix->string seconds . maybe-format)
  (apply date->string (time-utc->date (time-unix->time-utc seconds))
         maybe-format))
```

Credit @weinholt
## Usage
```scheme
; Loko
> (time-unix->string 946684800)
"Sat Jan 01 00:00:00Z 2000"
; Chez
> (time-unix->string 946684800)
"Sat Jan 01 02:00:00+0200 2000"
; Guile
> (time-unix->string 946684800)
$1 = "Sat Jan 01 01:00:00+0100 2000"
```

**Comment by weinholt** [comment]
This can be done with the time and date functions in SRFI 19. It is a bit trickier than it should be because SRFI 19 does not have a time type that corresponds to the Unix epoch, so we have to construct it manually by adding the number of seconds to 1970-01-01. Beware that I have only tested this on a handful of times.

```Scheme
(define (time-unix->time-utc seconds)
  (add-duration (date->time-utc (make-date 0 0 0 0 1 1 1970 0))
                (make-time time-duration 0 seconds)))

(define (time-unix->string seconds . maybe-format)
  (apply date->string (time-utc->date (time-unix->time-utc seconds))
         maybe-format))
```

Example: 

```scheme
; Loko
> (time-unix->string 946684800)
"Sat Jan 01 00:00:00Z 2000"
; Chez
> (time-unix->string 946684800)
"Sat Jan 01 02:00:00+0200 2000"
; Guile
> (time-unix->string 946684800)
$1 = "Sat Jan 01 01:00:00+0100 2000"
```

Looking at the output, I'm no longer sure where I am.

**Comment by lassik** [comment]
Thanks! That's awesome, every Scheme is in a different timezone!

**Comment by jcubic** [comment]
This can be improved to support formatting like in other languages where you have a grammar of tokens that make the date.
Example: `%Y-%D-%M`.

**Comment by lassik** [comment]
Committed into the file `format-unix-timestamp.md`.

**Comment by lassik** [comment]
Now at https://cookbook.scheme.org/format-unix-timestamp/
