### ISSUE TITLE
Macro similar to letrec but for macros

### ISSUE THREAD

**Issue by jcubic** [schemedoc/cookbook#2]
This is the first recipe that I've created using lisp macro.

The problem is that we want syntax similar to letrec but for macros (not that the same can be rewritten as a hygienic macro):

```scheme
(define-macro (let-macro macros . body)
  `(let ()
     ,@(map (lambda (macro)
              (if (and (symbol? (car macro))
                       (symbol=? (caadr macro) 'lambda))
                  (let ((name (car macro))
                        (args (cadadr macro))
                        (body (cddadr macro)))
                    `(define-macro (,name ,@args)
                       ,@body))
                   (error "let-macro: invalid syntax")))
            macros)
     (begin
       ,@body)))

(define (print . args)
  (for-each (lambda (arg)
              (display arg)
              (newline))
            args)

(let-macro ((foo (lambda (x) `'(,x ,x)))
            (bar (lambda (x y . rest) `(list ,x ,y ,@rest))))
   (print (list (foo a) (foo b) (bar 1 2 3 4))))
```

**Comment by lassik** [comment]
This is called [`macrolet`](http://www.lispworks.com/documentation/HyperSpec/Body/s_flet_.htm) in Common Lisp, and `let-syntax`/`letrec-syntax` in Scheme (R4RS and above). See for example [R7RS](https://standards.scheme.org/official/r7rs.pdf) page 22.

**Comment by jcubic** [comment]
I always thought that macrolet is for kind of symbol macros where symbols are expanded not as a macro call.

**Comment by jcubic** [comment]
It probably is not a good recipe because standard use hygienic macros.

**Comment by lassik** [comment]
That's a different concern. Common Lisp has a separate [`symbol-macrolet`](http://www.lispworks.com/documentation/HyperSpec/Body/s_symbol.htm) (and [`define-symbol-macro`](http://www.lispworks.com/documentation/HyperSpec/Body/m_defi_1.htm#define-symbol-macro) for global scope). In Scheme, [R6RS](https://standards.scheme.org/official/r6rs.pdf) has "identifier syntax" for the same purpose (page 59).

There are 4 different combinations:

* Normal macros for **global** scope (Scheme define-macro, or define-syntax with syntax-rules/syntax-case, Common Lisp defmacro).
* Normal macros for **local** scope (Scheme let-syntax/letrec-syntax, Common Lisp macrolet)
* Symbol macros (aka identifier syntax) for **global** scope (Scheme define-syntax with identifier-syntax, Common Lisp define-symbol-macro)
* Symbol macros (aka identifier syntax) for **local** scope (Scheme let-syntax/letrec-syntax with identifier-syntax, Common Lisp symbol-macrolet)

You could also distinguish between hygienic and unhygienic macros for more combinations :)

* let vs define = local vs global scope
* identifier-syntax or symbol-macro = identifier/symbol, others are normal macros
* the names with "syntax" are hygienic, the names with "macro" are unhygienic

Schemers usually use hygienic macros, but many do use unhygienic macros too. IMHO it's fine to also have unhygienic macros in a cookbook. Cookbooks' main purpose is to be useful, after all.

**Comment by lassik** [comment]
In Scheme, `define` can also be used inside a local scope, which adds a bit to the confusion. In Common Lisp, `define` is global only.
