### ISSUE TITLE
[Recipe] Searching sub string inside a string

### ISSUE THREAD

**Issue by jcubic** [schemedoc/cookbook#29]
## Problem

You want to search and find the index of a string inside a bigger string.

## Solution

```scheme
(define (string-find haystack needle . rest)
  (let ((start (if (null? rest) 0 (car rest))))
    (let* ((haystack-len (string-length haystack))
           (needle-len (string-length needle))
           (start 0))
      (let loop ((h-index start)
                 (n-index 0))
        (let ((h-char (string-ref haystack h-index))
              (n-char (string-ref needle n-index)))
          (if (char=? h-char n-char)
              (if (= (+ n-index 1) needle-len)
                  (+ (- h-index needle-len) 1)
                  (loop (+ h-index 1) (+ n-index 1)))
              (if (= (+ h-index 1) haystack-len)
                  #f
                  (loop (+ h-index 1) 0))))))))
```

### SRFI

The same functionality is provided by SRFI-13 function `string-contains` and `string-contains-ci`

Credit: @jcubic

## Usage

```scheme
(let* ((input "This is hello world")
       (search "hello")
       (found (string-find input search)))
  (if found
      (begin
        (display (substring input found))
        (newline))))
;; ==> "helo world"
```

**Comment by jcubic** [comment]
I was searching [SRFI-13](https://srfi.schemers.org/srfi-13/srfi-13.html) but it seems that search string is missing there is only searching for character

**Comment by jcubic** [comment]
I'm also not sure if `string->vector` is needed, I was trying to use `string-index` from SRFI, but it was way too complex.

**Comment by lassik** [comment]
[`string-contains`](https://srfi.schemers.org/srfi-13/srfi-13.html#string-contains) and `string-contains-ci` do it, they return the index where the substring appears. The names of these procedures are a bit confusing.
