### ISSUE TITLE
[Recipe] Find the index of an element in a list

### ISSUE THREAD

**Issue by jcubic** [schemedoc/cookbook#3]
## Problem
You have a list and a function and you want to find the first index for an item for which the function returns true.

## Solution:
```scheme
(define (list-index fn list)
  (let iter ((list list) (index 0))
    (if (null? list)
        -1
        (let ((item (car list)))
          (if (fn item)
              index
              (iter (cdr list) (+ index 1)))))))
```

Credit @jcubic

## SRFI

This function is defined in SRFI-1

## Usage
```scheme
(define >10 (lambda (x) (> x 10)))
(index >10 '(1 2 3 4 10 11 12 13 14))
;; ==> 5
```

**Comment by lassik** [comment]
This procedure is called [`list-index`](https://srfi.schemers.org/srfi-1/srfi-1.html#list-index) in SRFI 1.

**Comment by lassik** [comment]
Now at https://cookbook.scheme.org/find-index-of-element-in-list/
