### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by jcubic** [schemedoc/cookbook#33]
We need to decide what license the cookbook will have. Then we will need to add to the website footer (best on each recipe page) and into README and add a file with a license.

**Comment by lassik** [comment]
John Cowan said that it should be possible to license the code under multiple licenses in parallel: e.g. MIT, BSD, LGPL, and CC0.

**Comment by lassik** [comment]
That should be simplest for users, since a project that is already using MIT license (for example) can use it under MIT, and doesn't need to add a new license to their project just for the code they copied from the cookbook.

**Comment by lassik** [comment]
License info was added to the website in PR #50.
