### ISSUE TITLE
[Recipe] Creating subset of an AList

### ISSUE THREAD

**Issue by jcubic** [schemedoc/cookbook#4]
## Problem
You have Alist and you need to return the new Alist only with specified keys.

## Solution
```scheme
(define (match value)
  (lambda (x)
    (equal? x value)))

(define (alist->subset keys alist)
  (let iter ((alist alist) (keys keys) (result '()))
    (if (or (null? alist) (null? keys))
        (reverse result)
        (let* ((pair (car alist)) (key (car pair)))
          (if (member key keys)
              (let ((keys (remove (match keys) keys)))
                 (iter (cdr alist) keys (cons pair result)))
              (iter (cdr alist) keys result))))))
```
Credit @jcubic

It uses the `remove` function from Recipe #6

The code assumes that Alist has all unique keys.

## Usage
```scheme
(define alist '((foo . 10) (bar . 20) (baz . 30) (quux . 40)))
(alist->subset '(quux foo) alist)
;; => '((foo . 10) (quux . 40))
```

**Comment by lassik** [comment]
Alists are different from hash tables, in that an alist can have the same key more than once. For example, `((a . 1) (a . 2) (b .3))` is a valid alist, and this is sometimes used intentionally. Alist procedures that remove a key from the list should probably check for more than one occurrence of the same key, and remove all of them, unless it's a special optimized version.

**Comment by lassik** [comment]
That means the algorithm has O(n^2) complexity if you store the keys to check in a list. (O(n^2) is OK for small lists, but can be a problem with big lists). The algorithm I wrote in https://github.com/schemedoc/cookbook/issues/7#issuecomment-854992388 is also O(n^2) since it calls `assoc` (which is O(n)) inside the loop (also O(n)).

**Comment by lassik** [comment]
Now at https://cookbook.scheme.org/filter-alist-keys/
