### ISSUE TITLE
syntax-symbol?

### ISSUE THREAD

**Issue by jcubic** [schemedoc/cookbook#41]
@lassik What do you think about this macro [syntax-symbol?](http://community.schemewiki.org/?syntax-symbol%3f) it's based on [Oleg Kiselyov](http://okmij.org/ftp/Scheme/macros.html#macro-symbol-p). I've found it while searching for missing macros from [SRFI-46](https://srfi.schemers.org/srfi-46/srfi-46.html).

I think that if multiple people contributed to the final form of this macro, we can consider it Public Domain. We can credit Oleg. What you think?

**Comment by lassik** [comment]
Good idea! That macro is a classic :) We can assume it's public domain. It should be credited to Oleg, and according to the page you linked, maybe Al Petrofsky as well.

**Comment by lassik** [comment]
Now at https://cookbook.scheme.org/check-for-symbol-in-syntax-rules/
