### ISSUE TITLE
void value

### ISSUE THREAD

**Issue by jcubic** [schemedoc/cookbook#53]
I've seen this pattern in a book by Nils M Hom Sketchy Scheme. it can be written as a variable or as a macro:

```scheme
(define void (if #f #f))

(define-syntax void
  (syntax-rules ()
    ((_) (if #f #f))))
```

This is a way to get undefined (or to be precise unspecified by R7RS spec) value in Scheme.
But I'm not sure how much it's compatible with different scheme systems.

we can also add predicate:

```scheme
(define (void? x)
  (equal? (if #f #f) x))

(define (void? x)
  (equal? x void))
```

Tested in Chicken, Guile, and Kawa (that gives warning `warning - missing else where value is required`).

**Comment by lassik** [comment]
That's a good try for a portable void value, but it's not bulletproof since as you say, it's unspecified by the standard.

Here's a survey of what `(if #f #f)` returns: https://doc.scheme.org/surveys/OneArmedIf/

**Comment by lassik** [comment]
In general, https://doc.scheme.org/surveys/ (source https://github.com/schemedoc/surveys) is a good place to find out how different implementations do things. If you discover new stuff, PRs to that repo are very helpful to the Scheme community!

**Comment by lassik** [comment]
Here's a new one: https://github.com/schemedoc/surveys/pull/9

**Comment by lassik** [comment]
@jcubic According to https://doc.scheme.org/surveys/OneArmedIf/ `(if #f #f)` is not a very reliable way of getting void. Should we omit the recipe?

**Comment by jcubic** [comment]
I'm fine.

**Comment by lassik** [comment]
Thanks!
