### ISSUE TITLE
Do we have a need to standardize the options or part of the options for the top level script to run?

### ISSUE THREAD

**Issue by APIPLM** [schemedoc/cookbook#58]
As learning to run the top level script in the different implementation of Scheme, sound like there are different options available for me. But it takes a while for me to figure out what they are, how can it be used when running the script.  Sound like there is a need to standardize the options or part of them for the top level script to run. But is it possible for the implementors point view to do that? Or we already did it before?

**Comment by lassik** [comment]
It would be good to standardize them, but it's not possible (not yet, at least).

Most implementations support `foo-scheme bar.scm arg1 arg2 arg3 ...` But not all, for example:

* `chezscheme --program`
* `chicken -script`

There's a proposed standard for `#! /usr/bin/env scheme-script` but it's not useful for real work. It's a complex problem and a lot of experimentation is needed to find a good solution. My prototype is https://github.com/lispunion/lila but it's controversial.

**Comment by lassik** [comment]
See also https://github.com/schemedoc/guide/blob/master/portable-r7rs.adoc
