### ISSUE TITLE
[Recipe] Removing item from a list

### ISSUE THREAD

**Issue by jcubic** [schemedoc/cookbook#6]
## Problem
You have a list and want to remove items that return true for a given predicate function

## Solution
```scheme
(define (remove fn list)
  (let iter ((list list) (result '()))
    (if (null? list)
        (reverse result)
        (let ((item (car list)))
          (if (fn item)
              (iter (cdr list) result)
              (iter (cdr list) (cons item result)))))))
```
Credit @jcubic

### SRFI
This function is part of SRFI-1, which also has `filter` that is reverse of `remove`, where if the function returns `true` the item will be kept in the output list.

## Usage
```scheme
(define >10 (lambda (x) (> x 10)))
(remove >10 '(1 2 3 4 10 11 12 13 14))
;; ==> (1 2 3 4 10)
```

**Comment by lassik** [comment]
The code can be made shorter by putting the `if` inside the call to `(iter ...)`. The first argument, `(cdr list)`, is the same in both calls.

**Comment by lassik** [comment]
Also [`remove`](https://srfi.schemers.org/srfi-1/srfi-1.html#remove) in SRFI 1, as you probably noticed :)

**Comment by lassik** [comment]
Now at https://cookbook.scheme.org/remove-element-from-list/
